### PR TITLE
Print miniflare logs when tracing is enabled

### PR DESCRIPTION
**Pull request by tomasol**
# Description

Use the inherited stdout, stderr for the miniflare process when the CLI is started with `--trace 2`.
To preserve current behavior (debug messages of CLI), use `--trace 1` . Passing `2` will print miniflare logs as well.

# Type of change

- [ ] 💔 Breaking
- [ ] 🚀 Feature
- [x] 🐛 Fix
- [ ] 🛠️ Tooling
- [ ] 🔨 Refactoring
- [ ] 🧪 Test
- [ ] 📦 Dependency
- [ ] 📖 Requires documentation update

### CODE REVIEW

**Review by Finistere — APPROVED** [review]
That was long overdue, thanks!

**Comment by yoav-lavi** [comment]
Might be best to be able to separate these, perhaps an optional argument for `--trace`?

**Review by yoav-lavi — CHANGES_REQUESTED** [review]
I'd consider an argument for `--trace` that enables this, but let's discuss if others disagree

**Comment by yoav-lavi** [comment]
Another thing to consider here is that the tracing flag doesn't actually exist when we compile for release, but I'm not sure that distinction is still meaningful now that we plan to open source the worker.

**Review by yoav-lavi — APPROVED** [review]
Nice work!

**Pull request merged**
