### PR TITLE
chore: open-source internal crates

### PR DESCRIPTION
**Pull request by JeanMertz**
This PR open-sources a set of crates previously maintained internally by us. This is the first step towards creating a broader ecosystem around Grafbase and our tooling.

More to come. Stay tuned...

### CODE REVIEW

**Comment by yoav-lavi** [comment]
As discussed in Slack, I think it'd be a better idea to have the crates in a project directory rather than the root

**Comment by Finistere** [comment]
Haven't seen any discussion on it. A good chunk if not all is irrelevant to the CLI and only designed with EFS & dynamodb in mind. The relevant parts are already in this repo as it creates indices on the fly.

**Comment by obmarg** [comment]
Is there a way we could do this that doesn't get rid of all of the git history for the associated files?  Maybe [this](https://stackoverflow.com/a/17864475) to produce a clean repo with just the `oss` history followed by a subtree merge into `grafbase`?

**Comment by yoav-lavi** [comment]
@obmarg we discussed this, apparently it doesn't work since we moved the files to an oss dir so there's no history before that if you use filtering by dir. I still think we should look into it more though

**Comment by obmarg** [comment]
> @obmarg we discussed this, apparently it doesn't work since we moved the files to an oss dir so there's no history before that if you use filtering by dir. I still think we should look into it more though

[This answer certainly suggests we could be able to do _some_ kind of filtering to just a set of files](https://stackoverflow.com/a/32946929)

**Pull request closed without merging**
