### PR TITLE
chore(tests): Enable the 'preserve_order' feature flag for serde_json globally

### PR DESCRIPTION
**Pull request by jakubadamw**
# Description

This will help avoid map ordering issues relative to what directory the tests are ran from.

# Type of change

- [ ] 💔 Breaking
- [ ] 🚀 Feature
- [ ] 🐛 Fix
- [ ] 🛠️ Tooling
- [ ] 🔨 Refactoring
- [X] 🧪 Test
- [ ] 📦 Dependency
- [ ] 📖 Requires documentation update

### CODE REVIEW

**Comment by Finistere** [comment]
You have a bunch of unrelated commits in it^^

**Review by obmarg — APPROVED** [review]
Nice, thanks for handling this

**Comment by jakubadamw** [comment]
image

Quite an odd failure to be coming out of this

**Comment by obmarg** [comment]
> image
> Quite an odd failure to be coming out of this

Ah fuck.  That is actually expected.  `preserve_order` uses indexmap which is a few times larger than `BTreeMap`.

Now, I guess the question is will that bump in size start causing memory problems again (the reason I put that test there)

**Comment by jakubadamw** [comment]
I changed the test to use `more_asserts::assert_le`.

```
    #[test]
    fn test_graph_size() {
        // Our graph can end up with a ton of nodes & edges so it's important
        // that they don't get too big.
        more_asserts::assert_le!(std::mem::size_of::<Node>(), 48);
        more_asserts::assert_le!(std::mem::size_of::<Edge>(), 48);
    }
```

Somehow, this PR caused the memory size of `Node` to increase to 88.

```
--- STDERR:              parser-openapi graph::tests::test_graph_size ---
thread 'graph::tests::test_graph_size' panicked at engine/crates/parser-openapi/src/graph/mod.rs:597:9:
assertion failed: `(left <= right)`
  left: `88`,
 right: `48`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jakubadamw** [comment]
It's ultimately up to the compiler to decide on the memory layout, so I assume this effect isn't strictly related. @obmarg WDYT? Safe to increase?

**Comment by jakubadamw** [comment]
> That is actually expected. `preserve_order` uses indexmap which is a few times larger than `BTreeMap`.
> 
> Now, I guess the question is will that bump in size start causing memory problems again (the reason I put that test there)

Ah, of course, makes sense!

**Pull request merged**
